print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/jaredclark/Desktop/Target-Practice-161/Target Practice/Assets/Prefabs/TankModel.mb"`)
{		
	file -o "/Users/jaredclark/Desktop/Target-Practice-161/Target Practice/Assets/Prefabs/TankModel.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/jaredclark/Desktop/Target-Practice-161/Target Practice/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/jaredclark/Desktop/Target-Practice-161/Target Practice/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/jaredclark/Desktop/Target-Practice-161/Target Practice/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
